name: Daily INIS QA Check

on:
  schedule:
    # Run daily at 6:00 AM UTC (adjust timezone as needed)
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to process (YYYY-MM-DD, defaults to yesterday)'
        required: false
        type: string
  
jobs:
  qa-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run INIS QA Automation
      env:
        # Azure OpenAI Configuration
        AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
        ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
        DEPLOYMENT_NAME: ${{ secrets.DEPLOYMENT_NAME }}
        
        # Email Configuration
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
      run: |
        if [ -n "${{ github.event.inputs.date }}" ]; then
          python inis_daily_qa_automation.py --date "${{ github.event.inputs.date }}"
        else
          python inis_daily_qa_automation.py
        fi
        
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: qa-logs
        path: |
          *.log
          /tmp/inis_qa_*/
        retention-days: 7